### ISSUE TITLE
Using a single lineinfile to check a hostname-ip combination is not enough for correct address changing behaviour

### ISSUE THREAD

**Issue by Petrox** [weareinteractive/ansible-hosts#2]
Scenario:
 - I'd like to set "196.168.100.100" as the ip for "somehostname"
 - I run ansible
 - I recognize, that the correct IP would be "192.168.100.100" for "somehostname"

The current role only makes sure, that "192.168.100.100 somehostname" MUST BE PRESENT in the hosts file, if it isn't, then it inserts. But leaves the previous "196.168.100.100 somehostname" line intact.

This is not the way hosts file works, so a more sophisticated regexp based (lineinfile)removal mechanism is required.

(I did not yet found one hosts managing role at ansible-galaxy, that solves this better, so until I have time to play with this I'll just try not to change addresses.)

**Comment by franklinkim** [comment]
well, this role marks all entries it inserts into the hosts file with `#ansible` and removes ALL entries before managing them again. for example if you have this configuration:

```yaml
- hosts: all
  roles:
    - franklinkim.hosts
  vars:
    hosts:
      - { ip: '127.0.1.1', domain: 'foobar.com' }
```

the hosts file will look like:

```
127.0.0.1 localhost
...
127.0.1.1 foobar.com # ansible
```

if you change the configuration like:

```yaml
- hosts: all
  roles:
    - franklinkim.hosts
  vars:
    hosts:
      - { ip: '99.0.1.1', domain: 'foobar.com' }
```

it will look like:

```
127.0.0.1 localhost
...
99.0.1.1 foobar.com # ansible
```
hope this will lighten up your day a bit :)
